module ascon_datapath (
    input  wire         clk,
    input  wire         reset_n,         // Active-low synchronous reset

    // Control Signals (Driven by the FSM in Module 3)
    input  wire         ctrl_init_load,  // Load IV, Key, and Nonce into state
    input  wire         ctrl_update,     // Standard round: capture Permutation Core output
    input  wire         ctrl_inject,     // XOR incoming data into the rate (x0)
    input  wire         ctrl_key_xor,    // Phase transition: XOR Key into capacity

    // External Data Inputs
    input  wire [63:0]  data_in,         // 64-bit plaintext or associated data block
    input  wire [159:0] key,             // 160-bit Ascon-80pq Key
    input  wire [127:0] nonce,           // 128-bit Nonce

    // Connections FROM Combinational Permutation Core (Module 1)
    input  wire [63:0]  perm_x0, perm_x1, perm_x2, perm_x3, perm_x4,

    // Connections TO Combinational Permutation Core (Module 1)
    output reg  [63:0]  state_x0, state_x1, state_x2, state_x3, state_x4,

    // Data Output (Ciphertext / Plaintext extracted from the rate)
    output wire [63:0]  data_out
);

    // Ascon-80pq specific 32-bit IV (Key size=160, Rate=64, a=12, b=6)
    // Hex: 0xA0 (160), 0x40 (64), 0x0C (12), 0x06 (6)
    localparam [31:0] ASCON_80PQ_IV = 32'hA0400C06;

    // Output extraction: Ciphertext is generated by XORing plaintext with the permutation output
    assign data_out = perm_x0 ^ data_in;

    // Main Synchronous State Register Block
    always @(posedge clk) begin
        if (!reset_n) begin
            // Clear state on reset
            state_x0 <= 64'd0;
            state_x1 <= 64'd0;
            state_x2 <= 64'd0;
            state_x3 <= 64'd0;
            state_x4 <= 64'd0;
        end 
        else begin
            // Priority 1: Initialization Loading
            if (ctrl_init_load) begin
                state_x0 <= { ASCON_80PQ_IV, key[159:128] }; // 32-bit IV + Top 32 bits of Key
                state_x1 <= key[127:64];                     // Next 64 bits of Key
                state_x2 <= key[63:0];                       // Bottom 64 bits of Key
                state_x3 <= nonce[127:64];                   // Top 64 bits of Nonce
                state_x4 <= nonce[63:0];                     // Bottom 64 bits of Nonce
            end
            // Priority 2: Data Injection (Processing Associated Data or Plaintext)
            else if (ctrl_inject) begin
                state_x0 <= perm_x0 ^ data_in;               // XOR data into the 64-bit rate (x0)
                state_x1 <= perm_x1;                         // Capacity remains unchanged by data
                state_x2 <= perm_x2;
                state_x3 <= perm_x3;
                state_x4 <= perm_x4;
            end
            // Priority 3: Phase Transition Key XORing 
            // (Used at the end of initialization and beginning of finalization)
            else if (ctrl_key_xor) begin
                state_x0 <= perm_x0;
                // Ascon-80pq XORs the 160-bit key shifted across x1, x2, x3, x4
                state_x1 <= perm_x1 ^ { 32'd0, key[159:128] }; 
                state_x2 <= perm_x2 ^ key[127:64];
                state_x3 <= perm_x3 ^ key[63:0];
                state_x4 <= perm_x4; 
            end
            // Priority 4: Standard Permutation Loop
            else if (ctrl_update) begin
                state_x0 <= perm_x0;
                state_x1 <= perm_x1;
                state_x2 <= perm_x2;
                state_x3 <= perm_x3;
                state_x4 <= perm_x4;
            end
        end
    end

endmodule